-- MySQL Script generated by MySQL Workbench
-- Thu Jan  4 13:12:04 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Machine_cafe
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Machine_cafe
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Machine_cafe` DEFAULT CHARACTER SET utf8 ;
USE `Machine_cafe` ;

-- -----------------------------------------------------
-- Table `Machine_cafe`.`Boissons`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Machine_cafe`.`Boissons` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Prix` VARCHAR(45) NULL,
  `Libelle` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Machine_cafe`.`Ingredients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Machine_cafe`.`Ingredients` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Nom` VARCHAR(45) NULL,
  `Qty Stock` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Machine_cafe`.`Vente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Machine_cafe`.`Vente` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date_heure` DATE NULL,
  `Sucre` VARCHAR(45) NULL,
  `Boissons_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Vente_Boissons1_idx` (`Boissons_id` ASC),
  CONSTRAINT `fk_Vente_Boissons1`
    FOREIGN KEY (`Boissons_id`)
    REFERENCES `Machine_cafe`.`Boissons` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Machine_cafe`.`Ingredients_has_Boissons`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Machine_cafe`.`Ingredients_has_Boissons` (
  `Ingredients_id` INT NOT NULL,
  `Boissons_id` INT NOT NULL,
  `Qty` VARCHAR(45) NULL,
  PRIMARY KEY (`Ingredients_id`, `Boissons_id`),
  INDEX `fk_Ingredients_has_Boissons_Boissons1_idx` (`Boissons_id` ASC),
  INDEX `fk_Ingredients_has_Boissons_Ingredients_idx` (`Ingredients_id` ASC),
  CONSTRAINT `fk_Ingredients_has_Boissons_Ingredients`
    FOREIGN KEY (`Ingredients_id`)
    REFERENCES `Machine_cafe`.`Ingredients` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ingredients_has_Boissons_Boissons1`
    FOREIGN KEY (`Boissons_id`)
    REFERENCES `Machine_cafe`.`Boissons` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
